spring.application.name=bff-service
server.port=${BFF_SERVER_PORT:8080}

pulsehub.services.auth-service-url=${AUTH_SERVICE_URL:http://localhost:8082}
pulsehub.services.user-service-url=${USER_SERVICE_URL:http://localhost:8081}
pulsehub.services.message-service-url=${MESSAGE_SERVICE_URL:http://localhost:8083}

pulsehub.cors.allowed-origins=${BFF_CORS_ALLOWED_ORIGINS:http://localhost:3000}

auth.jwt.secret=${JWT_SECRET:dev-only-change-this-secret-for-pulsehub-auth-service}

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never
