spring.application.name=user-service
server.port=${SERVER_PORT:8081}

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5433/pulsehub_users}
spring.datasource.username=${DB_USERNAME:pulsehub}
spring.datasource.password=${DB_PASSWORD:pulsehub}

spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never

pulsehub.grpc.server.port=${USER_GRPC_SERVER_PORT:9091}
